const permissions = {
  createInstantInvite: 'Criar convites',
  kickMembers: 'Expulsar Membros',
  banMembers: 'Banir Membros',
  administrator: 'Administrador',
  manageChannels: 'Gerenciar Canal',
  manageGuild: 'Gerenciar Servidor',
  viewAuditLogs: 'Ver o registo de auditoria',
  voicePrioritySpeaker: 'Voz Prioritária',
  voiceStream: 'Transmitir',
  viewChannel: 'Ver Canal',
  sendMessages: 'Enviar Mensagens',
  sendTTSMessages: 'Enviar mensagens TTS',
  manageMessages: 'Gerenciar Mensagens',
  EMBED_LINKS: 'Inserir Links',
  attachFiles: 'Anexar Arquivos',
  readMessageHistory: 'Ler o histórico de mensagens',
  mentionEveryone: 'Mencionar everyone',
  useExternalEmojis: 'Usar emojis externos',
  useExternalStickers: 'Usar figurinhas externas',
  viewGuildInsights: 'Ver análises do servidor',
  voiceConnect: 'Conectar ao canal de voz',
  voiceSpeak: 'Falar no canal de voz',
  voiceMuteMembers: 'Silenciar Membros',
  voiceDeafenMembers: 'Ensurdecer Membros',
  voiceMoveMembers: 'Mover Membros',
  voiceUseVAD: 'Usar deteção de voz',
  changeNickname: 'Mudar de nickname',
  manageNicknames: 'Gerenciar nicknames',
  manageWebhooks: 'Gerenciar webhooks',
  manageEmojisAndStickers: 'Gerenciar Emojis e Stickers',
  useApplicationCommands: 'Usar comandos de aplicação',
  addReactions: 'Adicionar reações',
  manageRoles: 'Gerenciar Cargos',
  voiceRequestToSpeak: 'Requisitar para falar',
  manageThreads: 'Gerenciar Threads',
  createPublicThreads: 'Criar Threads públicas',
  createPrivateThreads: 'Criar Threads privadas',
  startEmbeddedActivities: 'Começar atividades',
  sendMessagesInThreads: 'Enviar mensagens em threads',
  // moderateMembers: 'Moderar Membros'
};

export default permissions;